version: '3.4'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:     
      - db
      - redis
    ports: 
      - 3000:3000
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems

  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest

  nginx:
    build: ./nginx
    depends_on:
      - app
    ports:
      - 443:443

volumes:
  gem_cache:
  db_data:
  node_modules: