default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "postgres") %>


test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "postgres_prod") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "postgres_prod") %>
