default: &default
  adapter: postgresql
  encoding: unicode
  username: rails_starter_template
  password:
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_starter_template_development


test:
  <<: *default
  database: rails_starter_template_test

production:
  <<: *default
  database: rails_starter_template_production
  username: rails_starter_template
  password: <%= ENV["RAILS_STARTER_TEMPLATE_DATABASE_PASSWORD"] %>
